name: Build shapez

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install FFmpeg
        uses: permanentdaylightt/setup-ffmpeg@main
        id: setup-ffmpeg

      - name: Install Yarn
        run: npm i yarn

      - name: Install dependencies
        run: |
          yarn
          cd electron
          yarn

      - name: Package application
        run: |
          cd ..
          yarn package-$PLATFORM-$ARCH
        env:
          PLATFORM: win32
          ARCH: x64

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: shapez-build
          path: build_output/standalone/shapez-*
